// // Sessions
// export const CREATE_SESSION_REQUEST = 'CREATE_SESSION_REQUEST';
// export const CREATE_SESSION_SUCCESS = 'CREATE_SESSION_SUCCESS';
// export const CREATE_SESSION_FAILURE = 'CREATE_SESSION_FAILURE';

// export const DELETE_SESSION_REQUEST = 'DELETE_SESSION_REQUEST';
// export const DELETE_SESSION_SUCCESS = 'DELETE_SESSION_SUCCESS';
// export const DELETE_SESSION_FAILURE = 'DELETE_SESSION_FAILURE';


// User action types
// export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
// export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
// export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';

// export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
// export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
// export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';

// export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
// export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
// export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';


// Document action types
export const FETCH_DOCUMENTS_REQUEST = 'FETCH_DOCUMENTS_REQUEST';
export const FETCH_DOCUMENTS_SUCCESS = 'FETCH_DOCUMENTS_SUCCESS';
export const FETCH_DOCUMENTS_FAILURE = 'FETCH_DOCUMENTS_FAILURE';

export const UPDATE_DOCUMENT_REQUEST = 'UPDATE_DOCUMENT_REQUEST';
export const UPDATE_DOCUMENT_SUCCESS = 'UPDATE_DOCUMENT_SUCCESS';
export const UPDATE_DOCUMENT_FAILURE = 'UPDATE_DOCUMENT_FAILURE';

export const ATTACH_DOCUMENT_REQUEST = 'ATTACH_DOCUMENT_REQUEST';
export const ATTACH_DOCUMENT_SUCCESS = 'ATTACH_DOCUMENT_SUCCESS';
export const ATTACH_DOCUMENT_FAILURE = 'ATTACH_DOCUMENT_FAILURE';

export const REMOVE_DOCUMENT_REQUEST = 'REMOVE_DOCUMENT_REQUEST';
export const REMOVE_DOCUMENT_SUCCESS = 'REMOVE_DOCUMENT_SUCCESS';
export const REMOVE_DOCUMENT_FAILURE = 'REMOVE_DOCUMENT_FAILURE';

export const DELETE_DOCUMENT_REQUEST = 'DELETE_DOCUMENT_REQUEST';
export const DELETE_DOCUMENT_SUCCESS = 'DELETE_DOCUMENT_SUCCESS';
export const DELETE_DOCUMENT_FAILURE = 'DELETE_DOCUMENT_FAILURE';


// Machine Instance
export const ADD_PART_REQUEST = 'ADD_PART_REQUEST';
export const ADD_PART_SUCCESS = 'ADD_PART_SUCCESS';
export const ADD_PART_FAILURE = 'ADD_PART_FAILURE';

export const EDIT_PART_QUANTITY_REQUEST = 'EDIT_PART_QUANTITY_REQUEST';
export const EDIT_PART_QUANTITY_SUCCESS = 'EDIT_PART_QUANTITY_SUCCESS';
export const EDIT_PART_QUANTITY_FAILURE = 'EDIT_PART_QUANTITY_FAILURE';

export const BULK_UPLOAD_REQUEST = 'BULK_UPLOAD_REQUEST';
export const BULK_UPLOAD_SUCCESS = 'BULK_UPLOAD_SUCCESS';
export const BULK_UPLOAD_FAILURE = 'BULK_UPLOAD_FAILURE';

export const ARCHIVE_MACHINE_INSTANCE_REQUEST = 'ARCHIVE_MACHINE_INSTANCE_REQUEST';
export const ARCHIVE_MACHINE_INSTANCE_SUCCESS = 'ARCHIVE_MACHINE_INSTANCE_SUCCESS';
export const ARCHIVE_MACHINE_INSTANCE_FAILURE = 'ARCHIVE_MACHINE_INSTANCE_FAILURE';

export const ATTACH_ASSEMBLY_REQUEST = 'ATTACH_ASSEMBLY_REQUEST';
export const ATTACH_ASSEMBLY_SUCCESS = 'ATTACH_ASSEMBLY_SUCCESS';
export const ATTACH_ASSEMBLY_FAILURE = 'ATTACH_ASSEMBLY_FAILURE';

export const FETCH_ARCHIVE_INDEX_REQUEST = 'FETCH_ARCHIVE_INDEX_REQUEST';
export const FETCH_ARCHIVE_INDEX_SUCCESS = 'FETCH_ARCHIVE_INDEX_SUCCESS';
export const FETCH_ARCHIVE_INDEX_FAILURE = 'FETCH_ARCHIVE_INDEX_FAILURE';

export const FETCH_MACHINE_INSTANCES_REQUEST = 'FETCH_MACHINE_INSTANCES_REQUEST';
export const FETCH_MACHINE_INSTANCES_SUCCESS = 'FETCH_MACHINE_INSTANCES_SUCCESS';
export const FETCH_MACHINE_INSTANCES_FAILURE = 'FETCH_MACHINE_INSTANCES_FAILURE';

export const CREATE_MACHINE_INSTANCE_REQUEST = 'CREATE_MACHINE_INSTANCE_REQUEST';
export const CREATE_MACHINE_INSTANCE_SUCCESS = 'CREATE_MACHINE_INSTANCE_SUCCESS';
export const CREATE_MACHINE_INSTANCE_FAILURE = 'CREATE_MACHINE_INSTANCE_FAILURE';

export const FETCH_NEW_MACHINE_INSTANCE_REQUEST = 'FETCH_NEW_MACHINE_INSTANCE_REQUEST';
export const FETCH_NEW_MACHINE_INSTANCE_SUCCESS = 'FETCH_NEW_MACHINE_INSTANCE_SUCCESS';
export const FETCH_NEW_MACHINE_INSTANCE_FAILURE = 'FETCH_NEW_MACHINE_INSTANCE_FAILURE';

export const FETCH_EDIT_MACHINE_INSTANCE_REQUEST = 'FETCH_EDIT_MACHINE_INSTANCE_REQUEST';
export const FETCH_EDIT_MACHINE_INSTANCE_SUCCESS = 'FETCH_EDIT_MACHINE_INSTANCE_SUCCESS';
export const FETCH_EDIT_MACHINE_INSTANCE_FAILURE = 'FETCH_EDIT_MACHINE_INSTANCE_FAILURE';

export const FETCH_MACHINE_INSTANCE_REQUEST = 'FETCH_MACHINE_INSTANCE_REQUEST';
export const FETCH_MACHINE_INSTANCE_SUCCESS = 'FETCH_MACHINE_INSTANCE_SUCCESS';
export const FETCH_MACHINE_INSTANCE_FAILURE = 'FETCH_MACHINE_INSTANCE_FAILURE';

export const UPDATE_MACHINE_INSTANCE_REQUEST = 'UPDATE_MACHINE_INSTANCE_REQUEST';
export const UPDATE_MACHINE_INSTANCE_SUCCESS = 'UPDATE_MACHINE_INSTANCE_SUCCESS';
export const UPDATE_MACHINE_INSTANCE_FAILURE = 'UPDATE_MACHINE_INSTANCE_FAILURE';

export const DELETE_MACHINE_INSTANCE_REQUEST = 'DELETE_MACHINE_INSTANCE_REQUEST';
export const DELETE_MACHINE_INSTANCE_SUCCESS = 'DELETE_MACHINE_INSTANCE_SUCCESS';
export const DELETE_MACHINE_INSTANCE_FAILURE = 'DELETE_MACHINE_INSTANCE_FAILURE';

// Machines
export const MACHINE_ADD_PART_REQUEST = 'MACHINE_ADD_PART_REQUEST';
export const MACHINE_ADD_PART_SUCCESS = 'MACHINE_ADD_PART_SUCCESS';
export const MACHINE_ADD_PART_FAILURE = 'MACHINE_ADD_PART_FAILURE';

export const MACHINE_EDIT_PART_QUANTITY_REQUEST = 'MACHINE_EDIT_PART_QUANTITY_REQUEST';
export const MACHINE_EDIT_PART_QUANTITY_SUCCESS = 'MACHINE_EDIT_PART_QUANTITY_SUCCESS';
export const MACHINE_EDIT_PART_QUANTITY_FAILURE = 'MACHINE_EDIT_PART_QUANTITY_FAILURE';

export const MACHINE_BULK_UPLOAD_REQUEST = 'MACHINE_BULK_UPLOAD_REQUEST';
export const MACHINE_BULK_UPLOAD_SUCCESS = 'MACHINE_BULK_UPLOAD_SUCCESS';
export const MACHINE_BULK_UPLOAD_FAILURE = 'MACHINE_BULK_UPLOAD_FAILURE';

export const MACHINE_ATTACH_ASSEMBLY_REQUEST = 'MACHINE_ATTACH_ASSEMBLY_REQUEST';
export const MACHINE_ATTACH_ASSEMBLY_SUCCESS = 'MACHINE_ATTACH_ASSEMBLY_SUCCESS';
export const MACHINE_ATTACH_ASSEMBLY_FAILURE = 'MACHINE_ATTACH_ASSEMBLY_FAILURE';

// Parts
export const FETCH_PARTS_REQUEST = 'FETCH_PARTS_REQUEST';
export const FETCH_PARTS_SUCCESS = 'FETCH_PARTS_SUCCESS';
export const FETCH_PARTS_FAILURE = 'FETCH_PARTS_FAILURE';

export const CREATE_PART_REQUEST = 'CREATE_PART_REQUEST';
export const CREATE_PART_SUCCESS = 'CREATE_PART_SUCCESS';
export const CREATE_PART_FAILURE = 'CREATE_PART_FAILURE';

export const UPDATE_PART_REQUEST = 'UPDATE_PART_REQUEST';
export const UPDATE_PART_SUCCESS = 'UPDATE_PART_SUCCESS';
export const UPDATE_PART_FAILURE = 'UPDATE_PART_FAILURE';

export const DELETE_PART_REQUEST = 'DELETE_PART_REQUEST';
export const DELETE_PART_SUCCESS = 'DELETE_PART_SUCCESS';
export const DELETE_PART_FAILURE = 'DELETE_PART_FAILURE';

// Groups
export const FETCH_GROUPS_REQUEST = 'FETCH_GROUPS_REQUEST';
export const FETCH_GROUPS_SUCCESS = 'FETCH_GROUPS_SUCCESS';
export const FETCH_GROUPS_FAILURE = 'FETCH_GROUPS_FAILURE';

export const CREATE_GROUP_REQUEST = 'CREATE_GROUP_REQUEST';
export const CREATE_GROUP_SUCCESS = 'CREATE_GROUP_SUCCESS';
export const CREATE_GROUP_FAILURE = 'CREATE_GROUP_FAILURE';

export const UPDATE_GROUP_REQUEST = 'UPDATE_GROUP_REQUEST';
export const UPDATE_GROUP_SUCCESS = 'UPDATE_GROUP_SUCCESS';
export const UPDATE_GROUP_FAILURE = 'UPDATE_GROUP_FAILURE';

export const DELETE_GROUP_REQUEST = 'DELETE_GROUP_REQUEST';
export const DELETE_GROUP_SUCCESS = 'DELETE_GROUP_SUCCESS';
export const DELETE_GROUP_FAILURE = 'DELETE_GROUP_FAILURE';

// Carts
export const FETCH_CARTS_REQUEST = 'FETCH_CARTS_REQUEST';
export const FETCH_CARTS_SUCCESS = 'FETCH_CARTS_SUCCESS';
export const FETCH_CARTS_FAILURE = 'FETCH_CARTS_FAILURE';

export const FETCH_CART_REQUEST = 'FETCH_CART_REQUEST';
export const FETCH_CART_SUCCESS = 'FETCH_CART_SUCCESS';
export const FETCH_CART_FAILURE = 'FETCH_CART_FAILURE';

export const REMOVE_MACHINE_FROM_CART_REQUEST = 'REMOVE_MACHINE_FROM_CART_REQUEST';
export const REMOVE_MACHINE_FROM_CART_SUCCESS = 'REMOVE_MACHINE_FROM_CART_SUCCESS';
export const REMOVE_MACHINE_FROM_CART_FAILURE = 'REMOVE_MACHINE_FROM_CART_FAILURE';

export const ADD_PART_TO_CART_REQUEST = 'ADD_PART_TO_CART_REQUEST';
export const ADD_PART_TO_CART_SUCCESS = 'ADD_PART_TO_CART_SUCCESS';
export const ADD_PART_TO_CART_FAILURE = 'ADD_PART_TO_CART_FAILURE';

export const ADD_PARTS_TO_CART_REQUEST = 'ADD_PARTS_TO_CART_REQUEST';
export const ADD_PARTS_TO_CART_SUCCESS = 'ADD_PARTS_TO_CART_SUCCESS';
export const ADD_PARTS_TO_CART_FAILURE = 'ADD_PARTS_TO_CART_FAILURE';

export const UPDATE_MANIFEST_REQUEST = 'UPDATE_MANIFEST_REQUEST';
export const UPDATE_MANIFEST_SUCCESS = 'UPDATE_MANIFEST_SUCCESS';
export const UPDATE_MANIFEST_FAILURE = 'UPDATE_MANIFEST_FAILURE';

export const ADD_MACHINE_TO_CART_REQUEST = 'ADD_MACHINE_TO_CART_REQUEST';
export const ADD_MACHINE_TO_CART_SUCCESS = 'ADD_MACHINE_TO_CART_SUCCESS';
export const ADD_MACHINE_TO_CART_FAILURE = 'ADD_MACHINE_TO_CART_FAILURE';

// Dashboards
export const FETCH_DASHBOARDS_REQUEST = 'FETCH_DASHBOARDS_REQUEST';
export const FETCH_DASHBOARDS_SUCCESS = 'FETCH_DASHBOARDS_SUCCESS';
export const FETCH_DASHBOARDS_FAILURE = 'FETCH_DASHBOARDS_FAILURE';

export const FETCH_AVAILABLE_PARTS_REQUEST = 'FETCH_AVAILABLE_PARTS_REQUEST';
export const FETCH_AVAILABLE_PARTS_SUCCESS = 'FETCH_AVAILABLE_PARTS_SUCCESS';
export const FETCH_AVAILABLE_PARTS_FAILURE = 'FETCH_AVAILABLE_PARTS_FAILURE';

export const FETCH_AVAILABLE_MACHINES_REQUEST = 'FETCH_AVAILABLE_MACHINES_REQUEST';
export const FETCH_AVAILABLE_MACHINES_SUCCESS = 'FETCH_AVAILABLE_MACHINES_SUCCESS';
export const FETCH_AVAILABLE_MACHINES_FAILURE = 'FETCH_AVAILABLE_MACHINES_FAILURE';

// Orders
export const FETCH_ORDERS_REQUEST = 'FETCH_ORDERS_REQUEST';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILURE = 'FETCH_ORDERS_FAILURE';

export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAILURE = 'CREATE_ORDER_FAILURE';

export const UPDATE_ORDER_REQUEST = 'UPDATE_ORDER_REQUEST';
export const UPDATE_ORDER_SUCCESS = 'UPDATE_ORDER_SUCCESS';
export const UPDATE_ORDER_FAILURE = 'UPDATE_ORDER_FAILURE';

export const DELETE_ORDER_REQUEST = 'DELETE_ORDER_REQUEST';
export const DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS';
export const DELETE_ORDER_FAILURE = 'DELETE_ORDER_FAILURE';

// Part Instances
export const FETCH_PART_INSTANCES_REQUEST = 'FETCH_PART_INSTANCES_REQUEST';
export const FETCH_PART_INSTANCES_SUCCESS = 'FETCH_PART_INSTANCES_SUCCESS';
export const FETCH_PART_INSTANCES_FAILURE = 'FETCH_PART_INSTANCES_FAILURE';

export const CREATE_PART_INSTANCE_REQUEST = 'CREATE_PART_INSTANCE_REQUEST';
export const CREATE_PART_INSTANCE_SUCCESS = 'CREATE_PART_INSTANCE_SUCCESS';
export const CREATE_PART_INSTANCE_FAILURE = 'CREATE_PART_INSTANCE_FAILURE';

export const UPDATE_PART_INSTANCE_REQUEST = 'UPDATE_PART_INSTANCE_REQUEST';
export const UPDATE_PART_INSTANCE_SUCCESS = 'UPDATE_PART_INSTANCE_SUCCESS';
export const UPDATE_PART_INSTANCE_FAILURE = 'UPDATE_PART_INSTANCE_FAILURE';

export const DELETE_PART_INSTANCE_REQUEST = 'DELETE_PART_INSTANCE_REQUEST';
export const DELETE_PART_INSTANCE_SUCCESS = 'DELETE_PART_INSTANCE_SUCCESS';
export const DELETE_PART_INSTANCE_FAILURE = 'DELETE_PART_INSTANCE_FAILURE';